---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    image: ami-04b9e92b5572fa0d1
    instance_type: t2.micro
    vpc_subnet_id: subnet-3d39d35a
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
    FILTERWARNINGS: "ignore::UserWarning"
  lint:
    name: flake8
  options:
    v: 1
